server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 28072004
    url: jdbc:postgresql://localhost:5432/Hotels
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create

